package com.me2me.ims.model;

import java.util.Date;

public class ImsFeature {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ims_feature.id
     *
     * @mbggenerated Wed Nov 22 09:43:38 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ims_feature.pid
     *
     * @mbggenerated Wed Nov 22 09:43:38 CST 2017
     */
    private Integer pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ims_feature.name
     *
     * @mbggenerated Wed Nov 22 09:43:38 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ims_feature.is_menu
     *
     * @mbggenerated Wed Nov 22 09:43:38 CST 2017
     */
    private Integer isMenu;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ims_feature.url
     *
     * @mbggenerated Wed Nov 22 09:43:38 CST 2017
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ims_feature.order_number
     *
     * @mbggenerated Wed Nov 22 09:43:38 CST 2017
     */
    private Integer orderNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ims_feature.sn
     *
     * @mbggenerated Wed Nov 22 09:43:38 CST 2017
     */
    private String sn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ims_feature.creation_date
     *
     * @mbggenerated Wed Nov 22 09:43:38 CST 2017
     */
    private Date creationDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ims_feature.id
     *
     * @return the value of ims_feature.id
     *
     * @mbggenerated Wed Nov 22 09:43:38 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ims_feature.id
     *
     * @param id the value for ims_feature.id
     *
     * @mbggenerated Wed Nov 22 09:43:38 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ims_feature.pid
     *
     * @return the value of ims_feature.pid
     *
     * @mbggenerated Wed Nov 22 09:43:38 CST 2017
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ims_feature.pid
     *
     * @param pid the value for ims_feature.pid
     *
     * @mbggenerated Wed Nov 22 09:43:38 CST 2017
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ims_feature.name
     *
     * @return the value of ims_feature.name
     *
     * @mbggenerated Wed Nov 22 09:43:38 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ims_feature.name
     *
     * @param name the value for ims_feature.name
     *
     * @mbggenerated Wed Nov 22 09:43:38 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ims_feature.is_menu
     *
     * @return the value of ims_feature.is_menu
     *
     * @mbggenerated Wed Nov 22 09:43:38 CST 2017
     */
    public Integer getIsMenu() {
        return isMenu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ims_feature.is_menu
     *
     * @param isMenu the value for ims_feature.is_menu
     *
     * @mbggenerated Wed Nov 22 09:43:38 CST 2017
     */
    public void setIsMenu(Integer isMenu) {
        this.isMenu = isMenu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ims_feature.url
     *
     * @return the value of ims_feature.url
     *
     * @mbggenerated Wed Nov 22 09:43:38 CST 2017
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ims_feature.url
     *
     * @param url the value for ims_feature.url
     *
     * @mbggenerated Wed Nov 22 09:43:38 CST 2017
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ims_feature.order_number
     *
     * @return the value of ims_feature.order_number
     *
     * @mbggenerated Wed Nov 22 09:43:38 CST 2017
     */
    public Integer getOrderNumber() {
        return orderNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ims_feature.order_number
     *
     * @param orderNumber the value for ims_feature.order_number
     *
     * @mbggenerated Wed Nov 22 09:43:38 CST 2017
     */
    public void setOrderNumber(Integer orderNumber) {
        this.orderNumber = orderNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ims_feature.sn
     *
     * @return the value of ims_feature.sn
     *
     * @mbggenerated Wed Nov 22 09:43:38 CST 2017
     */
    public String getSn() {
        return sn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ims_feature.sn
     *
     * @param sn the value for ims_feature.sn
     *
     * @mbggenerated Wed Nov 22 09:43:38 CST 2017
     */
    public void setSn(String sn) {
        this.sn = sn == null ? null : sn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ims_feature.creation_date
     *
     * @return the value of ims_feature.creation_date
     *
     * @mbggenerated Wed Nov 22 09:43:38 CST 2017
     */
    public Date getCreationDate() {
        return creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ims_feature.creation_date
     *
     * @param creationDate the value for ims_feature.creation_date
     *
     * @mbggenerated Wed Nov 22 09:43:38 CST 2017
     */
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }
}