package com.me2me.ims.model;

import java.util.Date;

public class ImsRole {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ims_role.id
     *
     * @mbggenerated Wed Nov 22 09:43:38 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ims_role.name
     *
     * @mbggenerated Wed Nov 22 09:43:38 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ims_role.create_time
     *
     * @mbggenerated Wed Nov 22 09:43:38 CST 2017
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ims_role.id
     *
     * @return the value of ims_role.id
     *
     * @mbggenerated Wed Nov 22 09:43:38 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ims_role.id
     *
     * @param id the value for ims_role.id
     *
     * @mbggenerated Wed Nov 22 09:43:38 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ims_role.name
     *
     * @return the value of ims_role.name
     *
     * @mbggenerated Wed Nov 22 09:43:38 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ims_role.name
     *
     * @param name the value for ims_role.name
     *
     * @mbggenerated Wed Nov 22 09:43:38 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ims_role.create_time
     *
     * @return the value of ims_role.create_time
     *
     * @mbggenerated Wed Nov 22 09:43:38 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ims_role.create_time
     *
     * @param createTime the value for ims_role.create_time
     *
     * @mbggenerated Wed Nov 22 09:43:38 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}