package com.me2me.ims.model;

import java.util.Date;

public class ImsUserLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ims_user_log.id
     *
     * @mbggenerated Wed Nov 22 09:43:38 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ims_user_log.user_id
     *
     * @mbggenerated Wed Nov 22 09:43:38 CST 2017
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ims_user_log.creation_date
     *
     * @mbggenerated Wed Nov 22 09:43:38 CST 2017
     */
    private Date creationDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ims_user_log.memo
     *
     * @mbggenerated Wed Nov 22 09:43:38 CST 2017
     */
    private String memo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ims_user_log.feature_id
     *
     * @mbggenerated Wed Nov 22 09:43:38 CST 2017
     */
    private Integer featureId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ims_user_log.id
     *
     * @return the value of ims_user_log.id
     *
     * @mbggenerated Wed Nov 22 09:43:38 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ims_user_log.id
     *
     * @param id the value for ims_user_log.id
     *
     * @mbggenerated Wed Nov 22 09:43:38 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ims_user_log.user_id
     *
     * @return the value of ims_user_log.user_id
     *
     * @mbggenerated Wed Nov 22 09:43:38 CST 2017
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ims_user_log.user_id
     *
     * @param userId the value for ims_user_log.user_id
     *
     * @mbggenerated Wed Nov 22 09:43:38 CST 2017
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ims_user_log.creation_date
     *
     * @return the value of ims_user_log.creation_date
     *
     * @mbggenerated Wed Nov 22 09:43:38 CST 2017
     */
    public Date getCreationDate() {
        return creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ims_user_log.creation_date
     *
     * @param creationDate the value for ims_user_log.creation_date
     *
     * @mbggenerated Wed Nov 22 09:43:38 CST 2017
     */
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ims_user_log.memo
     *
     * @return the value of ims_user_log.memo
     *
     * @mbggenerated Wed Nov 22 09:43:38 CST 2017
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ims_user_log.memo
     *
     * @param memo the value for ims_user_log.memo
     *
     * @mbggenerated Wed Nov 22 09:43:38 CST 2017
     */
    public void setMemo(String memo) {
        this.memo = memo == null ? null : memo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ims_user_log.feature_id
     *
     * @return the value of ims_user_log.feature_id
     *
     * @mbggenerated Wed Nov 22 09:43:38 CST 2017
     */
    public Integer getFeatureId() {
        return featureId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ims_user_log.feature_id
     *
     * @param featureId the value for ims_user_log.feature_id
     *
     * @mbggenerated Wed Nov 22 09:43:38 CST 2017
     */
    public void setFeatureId(Integer featureId) {
        this.featureId = featureId;
    }
}