package com.me2me.ims.model;

import java.util.Date;

public class ImsUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ims_user.id
     *
     * @mbggenerated Wed Nov 22 09:43:38 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ims_user.is_valid
     *
     * @mbggenerated Wed Nov 22 09:43:38 CST 2017
     */
    private Integer isValid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ims_user.creation_date
     *
     * @mbggenerated Wed Nov 22 09:43:38 CST 2017
     */
    private Date creationDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ims_user.user_name
     *
     * @mbggenerated Wed Nov 22 09:43:38 CST 2017
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ims_user.password
     *
     * @mbggenerated Wed Nov 22 09:43:38 CST 2017
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ims_user.true_name
     *
     * @mbggenerated Wed Nov 22 09:43:38 CST 2017
     */
    private String trueName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ims_user.mobile
     *
     * @mbggenerated Wed Nov 22 09:43:38 CST 2017
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ims_user.address
     *
     * @mbggenerated Wed Nov 22 09:43:38 CST 2017
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ims_user.email
     *
     * @mbggenerated Wed Nov 22 09:43:38 CST 2017
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ims_user.sex
     *
     * @mbggenerated Wed Nov 22 09:43:38 CST 2017
     */
    private Integer sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ims_user.photo
     *
     * @mbggenerated Wed Nov 22 09:43:38 CST 2017
     */
    private String photo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ims_user.group_id
     *
     * @mbggenerated Wed Nov 22 09:43:38 CST 2017
     */
    private Integer groupId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ims_user.id
     *
     * @return the value of ims_user.id
     *
     * @mbggenerated Wed Nov 22 09:43:38 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ims_user.id
     *
     * @param id the value for ims_user.id
     *
     * @mbggenerated Wed Nov 22 09:43:38 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ims_user.is_valid
     *
     * @return the value of ims_user.is_valid
     *
     * @mbggenerated Wed Nov 22 09:43:38 CST 2017
     */
    public Integer getIsValid() {
        return isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ims_user.is_valid
     *
     * @param isValid the value for ims_user.is_valid
     *
     * @mbggenerated Wed Nov 22 09:43:38 CST 2017
     */
    public void setIsValid(Integer isValid) {
        this.isValid = isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ims_user.creation_date
     *
     * @return the value of ims_user.creation_date
     *
     * @mbggenerated Wed Nov 22 09:43:38 CST 2017
     */
    public Date getCreationDate() {
        return creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ims_user.creation_date
     *
     * @param creationDate the value for ims_user.creation_date
     *
     * @mbggenerated Wed Nov 22 09:43:38 CST 2017
     */
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ims_user.user_name
     *
     * @return the value of ims_user.user_name
     *
     * @mbggenerated Wed Nov 22 09:43:38 CST 2017
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ims_user.user_name
     *
     * @param userName the value for ims_user.user_name
     *
     * @mbggenerated Wed Nov 22 09:43:38 CST 2017
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ims_user.password
     *
     * @return the value of ims_user.password
     *
     * @mbggenerated Wed Nov 22 09:43:38 CST 2017
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ims_user.password
     *
     * @param password the value for ims_user.password
     *
     * @mbggenerated Wed Nov 22 09:43:38 CST 2017
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ims_user.true_name
     *
     * @return the value of ims_user.true_name
     *
     * @mbggenerated Wed Nov 22 09:43:38 CST 2017
     */
    public String getTrueName() {
        return trueName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ims_user.true_name
     *
     * @param trueName the value for ims_user.true_name
     *
     * @mbggenerated Wed Nov 22 09:43:38 CST 2017
     */
    public void setTrueName(String trueName) {
        this.trueName = trueName == null ? null : trueName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ims_user.mobile
     *
     * @return the value of ims_user.mobile
     *
     * @mbggenerated Wed Nov 22 09:43:38 CST 2017
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ims_user.mobile
     *
     * @param mobile the value for ims_user.mobile
     *
     * @mbggenerated Wed Nov 22 09:43:38 CST 2017
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ims_user.address
     *
     * @return the value of ims_user.address
     *
     * @mbggenerated Wed Nov 22 09:43:38 CST 2017
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ims_user.address
     *
     * @param address the value for ims_user.address
     *
     * @mbggenerated Wed Nov 22 09:43:38 CST 2017
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ims_user.email
     *
     * @return the value of ims_user.email
     *
     * @mbggenerated Wed Nov 22 09:43:38 CST 2017
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ims_user.email
     *
     * @param email the value for ims_user.email
     *
     * @mbggenerated Wed Nov 22 09:43:38 CST 2017
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ims_user.sex
     *
     * @return the value of ims_user.sex
     *
     * @mbggenerated Wed Nov 22 09:43:38 CST 2017
     */
    public Integer getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ims_user.sex
     *
     * @param sex the value for ims_user.sex
     *
     * @mbggenerated Wed Nov 22 09:43:38 CST 2017
     */
    public void setSex(Integer sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ims_user.photo
     *
     * @return the value of ims_user.photo
     *
     * @mbggenerated Wed Nov 22 09:43:38 CST 2017
     */
    public String getPhoto() {
        return photo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ims_user.photo
     *
     * @param photo the value for ims_user.photo
     *
     * @mbggenerated Wed Nov 22 09:43:38 CST 2017
     */
    public void setPhoto(String photo) {
        this.photo = photo == null ? null : photo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ims_user.group_id
     *
     * @return the value of ims_user.group_id
     *
     * @mbggenerated Wed Nov 22 09:43:38 CST 2017
     */
    public Integer getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ims_user.group_id
     *
     * @param groupId the value for ims_user.group_id
     *
     * @mbggenerated Wed Nov 22 09:43:38 CST 2017
     */
    public void setGroupId(Integer groupId) {
        this.groupId = groupId;
    }
}