package com.me2me.ims.model;

public class UserOrganizationInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_organization_info.id
     *
     * @mbggenerated Mon Nov 20 17:28:10 CST 2017
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_organization_info.uid
     *
     * @mbggenerated Mon Nov 20 17:28:10 CST 2017
     */
    private Long uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_organization_info.organization_id
     *
     * @mbggenerated Mon Nov 20 17:28:10 CST 2017
     */
    private Long organizationId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_organization_info.organization_number
     *
     * @mbggenerated Mon Nov 20 17:28:10 CST 2017
     */
    private String organizationNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_organization_info.user_name
     *
     * @mbggenerated Mon Nov 20 17:28:10 CST 2017
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_organization_info.gender
     *
     * @mbggenerated Mon Nov 20 17:28:10 CST 2017
     */
    private Integer gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_organization_info.wechat_name
     *
     * @mbggenerated Mon Nov 20 17:28:10 CST 2017
     */
    private String wechatName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_organization_info.wechat_number
     *
     * @mbggenerated Mon Nov 20 17:28:10 CST 2017
     */
    private String wechatNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_organization_info.mobile1
     *
     * @mbggenerated Mon Nov 20 17:28:10 CST 2017
     */
    private String mobile1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_organization_info.mobile2
     *
     * @mbggenerated Mon Nov 20 17:28:10 CST 2017
     */
    private String mobile2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_organization_info.birthday
     *
     * @mbggenerated Mon Nov 20 17:28:10 CST 2017
     */
    private String birthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_organization_info.age
     *
     * @mbggenerated Mon Nov 20 17:28:10 CST 2017
     */
    private Integer age;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_organization_info.address
     *
     * @mbggenerated Mon Nov 20 17:28:10 CST 2017
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_organization_info.remark1
     *
     * @mbggenerated Mon Nov 20 17:28:10 CST 2017
     */
    private String remark1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_organization_info.remark2
     *
     * @mbggenerated Mon Nov 20 17:28:10 CST 2017
     */
    private String remark2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_organization_info.remark3
     *
     * @mbggenerated Mon Nov 20 17:28:10 CST 2017
     */
    private String remark3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_organization_info.remark4
     *
     * @mbggenerated Mon Nov 20 17:28:10 CST 2017
     */
    private String remark4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_organization_info.out_remark1
     *
     * @mbggenerated Mon Nov 20 17:28:10 CST 2017
     */
    private String outRemark1;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_organization_info.id
     *
     * @return the value of user_organization_info.id
     *
     * @mbggenerated Mon Nov 20 17:28:10 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_organization_info.id
     *
     * @param id the value for user_organization_info.id
     *
     * @mbggenerated Mon Nov 20 17:28:10 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_organization_info.uid
     *
     * @return the value of user_organization_info.uid
     *
     * @mbggenerated Mon Nov 20 17:28:10 CST 2017
     */
    public Long getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_organization_info.uid
     *
     * @param uid the value for user_organization_info.uid
     *
     * @mbggenerated Mon Nov 20 17:28:10 CST 2017
     */
    public void setUid(Long uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_organization_info.organization_id
     *
     * @return the value of user_organization_info.organization_id
     *
     * @mbggenerated Mon Nov 20 17:28:10 CST 2017
     */
    public Long getOrganizationId() {
        return organizationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_organization_info.organization_id
     *
     * @param organizationId the value for user_organization_info.organization_id
     *
     * @mbggenerated Mon Nov 20 17:28:10 CST 2017
     */
    public void setOrganizationId(Long organizationId) {
        this.organizationId = organizationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_organization_info.organization_number
     *
     * @return the value of user_organization_info.organization_number
     *
     * @mbggenerated Mon Nov 20 17:28:10 CST 2017
     */
    public String getOrganizationNumber() {
        return organizationNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_organization_info.organization_number
     *
     * @param organizationNumber the value for user_organization_info.organization_number
     *
     * @mbggenerated Mon Nov 20 17:28:10 CST 2017
     */
    public void setOrganizationNumber(String organizationNumber) {
        this.organizationNumber = organizationNumber == null ? null : organizationNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_organization_info.user_name
     *
     * @return the value of user_organization_info.user_name
     *
     * @mbggenerated Mon Nov 20 17:28:10 CST 2017
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_organization_info.user_name
     *
     * @param userName the value for user_organization_info.user_name
     *
     * @mbggenerated Mon Nov 20 17:28:10 CST 2017
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_organization_info.gender
     *
     * @return the value of user_organization_info.gender
     *
     * @mbggenerated Mon Nov 20 17:28:10 CST 2017
     */
    public Integer getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_organization_info.gender
     *
     * @param gender the value for user_organization_info.gender
     *
     * @mbggenerated Mon Nov 20 17:28:10 CST 2017
     */
    public void setGender(Integer gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_organization_info.wechat_name
     *
     * @return the value of user_organization_info.wechat_name
     *
     * @mbggenerated Mon Nov 20 17:28:10 CST 2017
     */
    public String getWechatName() {
        return wechatName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_organization_info.wechat_name
     *
     * @param wechatName the value for user_organization_info.wechat_name
     *
     * @mbggenerated Mon Nov 20 17:28:10 CST 2017
     */
    public void setWechatName(String wechatName) {
        this.wechatName = wechatName == null ? null : wechatName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_organization_info.wechat_number
     *
     * @return the value of user_organization_info.wechat_number
     *
     * @mbggenerated Mon Nov 20 17:28:10 CST 2017
     */
    public String getWechatNumber() {
        return wechatNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_organization_info.wechat_number
     *
     * @param wechatNumber the value for user_organization_info.wechat_number
     *
     * @mbggenerated Mon Nov 20 17:28:10 CST 2017
     */
    public void setWechatNumber(String wechatNumber) {
        this.wechatNumber = wechatNumber == null ? null : wechatNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_organization_info.mobile1
     *
     * @return the value of user_organization_info.mobile1
     *
     * @mbggenerated Mon Nov 20 17:28:10 CST 2017
     */
    public String getMobile1() {
        return mobile1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_organization_info.mobile1
     *
     * @param mobile1 the value for user_organization_info.mobile1
     *
     * @mbggenerated Mon Nov 20 17:28:10 CST 2017
     */
    public void setMobile1(String mobile1) {
        this.mobile1 = mobile1 == null ? null : mobile1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_organization_info.mobile2
     *
     * @return the value of user_organization_info.mobile2
     *
     * @mbggenerated Mon Nov 20 17:28:10 CST 2017
     */
    public String getMobile2() {
        return mobile2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_organization_info.mobile2
     *
     * @param mobile2 the value for user_organization_info.mobile2
     *
     * @mbggenerated Mon Nov 20 17:28:10 CST 2017
     */
    public void setMobile2(String mobile2) {
        this.mobile2 = mobile2 == null ? null : mobile2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_organization_info.birthday
     *
     * @return the value of user_organization_info.birthday
     *
     * @mbggenerated Mon Nov 20 17:28:10 CST 2017
     */
    public String getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_organization_info.birthday
     *
     * @param birthday the value for user_organization_info.birthday
     *
     * @mbggenerated Mon Nov 20 17:28:10 CST 2017
     */
    public void setBirthday(String birthday) {
        this.birthday = birthday == null ? null : birthday.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_organization_info.age
     *
     * @return the value of user_organization_info.age
     *
     * @mbggenerated Mon Nov 20 17:28:10 CST 2017
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_organization_info.age
     *
     * @param age the value for user_organization_info.age
     *
     * @mbggenerated Mon Nov 20 17:28:10 CST 2017
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_organization_info.address
     *
     * @return the value of user_organization_info.address
     *
     * @mbggenerated Mon Nov 20 17:28:10 CST 2017
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_organization_info.address
     *
     * @param address the value for user_organization_info.address
     *
     * @mbggenerated Mon Nov 20 17:28:10 CST 2017
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_organization_info.remark1
     *
     * @return the value of user_organization_info.remark1
     *
     * @mbggenerated Mon Nov 20 17:28:10 CST 2017
     */
    public String getRemark1() {
        return remark1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_organization_info.remark1
     *
     * @param remark1 the value for user_organization_info.remark1
     *
     * @mbggenerated Mon Nov 20 17:28:10 CST 2017
     */
    public void setRemark1(String remark1) {
        this.remark1 = remark1 == null ? null : remark1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_organization_info.remark2
     *
     * @return the value of user_organization_info.remark2
     *
     * @mbggenerated Mon Nov 20 17:28:10 CST 2017
     */
    public String getRemark2() {
        return remark2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_organization_info.remark2
     *
     * @param remark2 the value for user_organization_info.remark2
     *
     * @mbggenerated Mon Nov 20 17:28:10 CST 2017
     */
    public void setRemark2(String remark2) {
        this.remark2 = remark2 == null ? null : remark2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_organization_info.remark3
     *
     * @return the value of user_organization_info.remark3
     *
     * @mbggenerated Mon Nov 20 17:28:10 CST 2017
     */
    public String getRemark3() {
        return remark3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_organization_info.remark3
     *
     * @param remark3 the value for user_organization_info.remark3
     *
     * @mbggenerated Mon Nov 20 17:28:10 CST 2017
     */
    public void setRemark3(String remark3) {
        this.remark3 = remark3 == null ? null : remark3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_organization_info.remark4
     *
     * @return the value of user_organization_info.remark4
     *
     * @mbggenerated Mon Nov 20 17:28:10 CST 2017
     */
    public String getRemark4() {
        return remark4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_organization_info.remark4
     *
     * @param remark4 the value for user_organization_info.remark4
     *
     * @mbggenerated Mon Nov 20 17:28:10 CST 2017
     */
    public void setRemark4(String remark4) {
        this.remark4 = remark4 == null ? null : remark4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_organization_info.out_remark1
     *
     * @return the value of user_organization_info.out_remark1
     *
     * @mbggenerated Mon Nov 20 17:28:10 CST 2017
     */
    public String getOutRemark1() {
        return outRemark1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_organization_info.out_remark1
     *
     * @param outRemark1 the value for user_organization_info.out_remark1
     *
     * @mbggenerated Mon Nov 20 17:28:10 CST 2017
     */
    public void setOutRemark1(String outRemark1) {
        this.outRemark1 = outRemark1 == null ? null : outRemark1.trim();
    }
}