package com.me2me.ims.mapper.auto;

import com.me2me.ims.model.ImsRole;
import com.me2me.ims.model.ImsRoleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ImsRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ims_role
     *
     * @mbggenerated Wed Nov 22 09:43:38 CST 2017
     */
    int countByExample(ImsRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ims_role
     *
     * @mbggenerated Wed Nov 22 09:43:38 CST 2017
     */
    int deleteByExample(ImsRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ims_role
     *
     * @mbggenerated Wed Nov 22 09:43:38 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ims_role
     *
     * @mbggenerated Wed Nov 22 09:43:38 CST 2017
     */
    int insert(ImsRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ims_role
     *
     * @mbggenerated Wed Nov 22 09:43:38 CST 2017
     */
    int insertSelective(ImsRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ims_role
     *
     * @mbggenerated Wed Nov 22 09:43:38 CST 2017
     */
    List<ImsRole> selectByExample(ImsRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ims_role
     *
     * @mbggenerated Wed Nov 22 09:43:38 CST 2017
     */
    ImsRole selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ims_role
     *
     * @mbggenerated Wed Nov 22 09:43:38 CST 2017
     */
    int updateByExampleSelective(@Param("record") ImsRole record, @Param("example") ImsRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ims_role
     *
     * @mbggenerated Wed Nov 22 09:43:38 CST 2017
     */
    int updateByExample(@Param("record") ImsRole record, @Param("example") ImsRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ims_role
     *
     * @mbggenerated Wed Nov 22 09:43:38 CST 2017
     */
    int updateByPrimaryKeySelective(ImsRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ims_role
     *
     * @mbggenerated Wed Nov 22 09:43:38 CST 2017
     */
    int updateByPrimaryKey(ImsRole record);
}