package com.me2me.ims.mapper.auto;

import com.me2me.ims.model.ImsUser;
import com.me2me.ims.model.ImsUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ImsUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ims_user
     *
     * @mbggenerated Wed Nov 22 09:43:38 CST 2017
     */
    int countByExample(ImsUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ims_user
     *
     * @mbggenerated Wed Nov 22 09:43:38 CST 2017
     */
    int deleteByExample(ImsUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ims_user
     *
     * @mbggenerated Wed Nov 22 09:43:38 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ims_user
     *
     * @mbggenerated Wed Nov 22 09:43:38 CST 2017
     */
    int insert(ImsUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ims_user
     *
     * @mbggenerated Wed Nov 22 09:43:38 CST 2017
     */
    int insertSelective(ImsUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ims_user
     *
     * @mbggenerated Wed Nov 22 09:43:38 CST 2017
     */
    List<ImsUser> selectByExample(ImsUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ims_user
     *
     * @mbggenerated Wed Nov 22 09:43:38 CST 2017
     */
    ImsUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ims_user
     *
     * @mbggenerated Wed Nov 22 09:43:38 CST 2017
     */
    int updateByExampleSelective(@Param("record") ImsUser record, @Param("example") ImsUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ims_user
     *
     * @mbggenerated Wed Nov 22 09:43:38 CST 2017
     */
    int updateByExample(@Param("record") ImsUser record, @Param("example") ImsUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ims_user
     *
     * @mbggenerated Wed Nov 22 09:43:38 CST 2017
     */
    int updateByPrimaryKeySelective(ImsUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ims_user
     *
     * @mbggenerated Wed Nov 22 09:43:38 CST 2017
     */
    int updateByPrimaryKey(ImsUser record);
}