package com.me2me.ims.mapper.auto;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.me2me.ims.model.UserOrganization;
import com.me2me.ims.model.UserOrganizationExample;
import com.me2me.user.dto.SearchUserOrganizationDto;

public interface UserOrganizationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_organization
     *
     * @mbggenerated Wed Nov 22 09:43:38 CST 2017
     */
    int countByExample(UserOrganizationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_organization
     *
     * @mbggenerated Wed Nov 22 09:43:38 CST 2017
     */
    int deleteByExample(UserOrganizationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_organization
     *
     * @mbggenerated Wed Nov 22 09:43:38 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_organization
     *
     * @mbggenerated Wed Nov 22 09:43:38 CST 2017
     */
    int insert(UserOrganization record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_organization
     *
     * @mbggenerated Wed Nov 22 09:43:38 CST 2017
     */
    int insertSelective(UserOrganization record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_organization
     *
     * @mbggenerated Wed Nov 22 09:43:38 CST 2017
     */
    List<UserOrganization> selectByExample(UserOrganizationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_organization
     *
     * @mbggenerated Wed Nov 22 09:43:38 CST 2017
     */
    UserOrganization selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_organization
     *
     * @mbggenerated Wed Nov 22 09:43:38 CST 2017
     */
    int updateByExampleSelective(@Param("record") UserOrganization record, @Param("example") UserOrganizationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_organization
     *
     * @mbggenerated Wed Nov 22 09:43:38 CST 2017
     */
    int updateByExample(@Param("record") UserOrganization record, @Param("example") UserOrganizationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_organization
     *
     * @mbggenerated Wed Nov 22 09:43:38 CST 2017
     */
    int updateByPrimaryKeySelective(UserOrganization record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_organization
     *
     * @mbggenerated Wed Nov 22 09:43:38 CST 2017
     */
    int updateByPrimaryKey(UserOrganization record);
    
    List<SearchUserOrganizationDto> searchUserPage(Map<String, Object> queries);
    
    int countSearchUserPage (Map<String, Object> queries);
}