package com.me2me.ims.mapper.auto;

import com.me2me.ims.model.UserOrganizationInfo;
import com.me2me.ims.model.UserOrganizationInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserOrganizationInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_organization_info
     *
     * @mbggenerated Mon Nov 20 17:28:10 CST 2017
     */
    int countByExample(UserOrganizationInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_organization_info
     *
     * @mbggenerated Mon Nov 20 17:28:10 CST 2017
     */
    int deleteByExample(UserOrganizationInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_organization_info
     *
     * @mbggenerated Mon Nov 20 17:28:10 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_organization_info
     *
     * @mbggenerated Mon Nov 20 17:28:10 CST 2017
     */
    int insert(UserOrganizationInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_organization_info
     *
     * @mbggenerated Mon Nov 20 17:28:10 CST 2017
     */
    int insertSelective(UserOrganizationInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_organization_info
     *
     * @mbggenerated Mon Nov 20 17:28:10 CST 2017
     */
    List<UserOrganizationInfo> selectByExample(UserOrganizationInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_organization_info
     *
     * @mbggenerated Mon Nov 20 17:28:10 CST 2017
     */
    UserOrganizationInfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_organization_info
     *
     * @mbggenerated Mon Nov 20 17:28:10 CST 2017
     */
    int updateByExampleSelective(@Param("record") UserOrganizationInfo record, @Param("example") UserOrganizationInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_organization_info
     *
     * @mbggenerated Mon Nov 20 17:28:10 CST 2017
     */
    int updateByExample(@Param("record") UserOrganizationInfo record, @Param("example") UserOrganizationInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_organization_info
     *
     * @mbggenerated Mon Nov 20 17:28:10 CST 2017
     */
    int updateByPrimaryKeySelective(UserOrganizationInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_organization_info
     *
     * @mbggenerated Mon Nov 20 17:28:10 CST 2017
     */
    int updateByPrimaryKey(UserOrganizationInfo record);
}